### ISSUE TITLE
در صورت ایجاد آی دی جدید کدام تابع فراخوانی می شود ؟

### ISSUE THREAD

**Issue by adelhoss** [pusheco/android-sdk#1]
با سلام
و عرض خسته نباشید خدمت شما بزرگواران و عزیزان زحمت کش
دوستان همان طور که اطلاع دارید در اندروید با کلیر دیتا کردن برنامه
ای دی جدیدی ایجاد خواهد شد
clear data
یک pusheid
جدید تولید خواهد شد
ما چگونه از ایجاد شدن ای دی جدید باخبر شویم ؟

**Comment by mahdi-malv** [comment]
<div dir='rtl'>

سلام

توی [این لینک](https://github.com/pusheco/android-studio-sample/issues/15) می‌تونید بحث رو دنبال  کنید.

باتشکر.

</div>
